import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { jobExperience, certifications } from '../data/constants'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Portfolio.Olugbade Qudus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <div className={styles.introBox}>
      <h1>Olugbade Qudus</h1>
      <p className={styles.intro}>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt nisi
        architecto atque ab labore quo repellat, nam in iusto assumenda tenetur
        cupiditate, perferendis recusandae. Deserunt.
      </p>
    </div>

    <div className={styles.certificationsBox}>
      <h3>Certifications</h3>
      <ul>
        {certifications.map((item, idx)=>{
          return (
            <li key={idx}>{item}</li>
          )
        })}
      </ul>
    </div>

    <div className={styles.jobExperience}>
      <h3>Job Experience</h3>
      <ul>
        {jobExperience.map((item, idx)=>{
          return (
            <li key={idx}>{item}</li>
          )
        })}
      </ul>
    </div>

      <div className={styles.sideProjects}>
        <h3>Side Projects</h3>

        <p>Lorem ipsum dolor sit amet consectetur.</p>
        <p>Lorem ipsum dolor sit amet consectetur.</p>
        <p>Lorem ipsum dolor sit amet consectetur.</p>
      </div>
    </div>
  );
}

export default Home
